# Generated by Django 4.1 on 2022-09-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Адрес')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('role', models.CharField(choices=[('seller', 'Продавец'), ('buyer', 'Покупатель')], max_length=6, verbose_name='Должность')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
